"""Annotation-denied export and startup guard; imports here are stdlib-only."""
from __future__ import annotations

import os
import sys
from pathlib import Path

_ANNOTATION_GUARDS = {}


def forbidden_path(path, allowed_geff_root=None):
    """Resolve aliases before checking labels and evaluation-only artifacts."""
    path = Path(os.fsdecode(path)).absolute().resolve()
    text = str(path).lower()
    if '.geff' in text:
        if allowed_geff_root is None or not path.is_relative_to(Path(allowed_geff_root).resolve()):
            return True
    parts = set(path.parts)
    return (bool(parts & {'evaluation', 'oracles', 'oracle', 'census'})
            or path.name == 'inventory.json'
            or any(token in path.name for token in ['training_labels', 'source_labels.parquet',
                                                     'score_rows', 'division_census', 'edge_census']))


def deny_annotations(allowed_geff_root=None):
    key = str(Path(allowed_geff_root).resolve()) if allowed_geff_root is not None else None
    if key in _ANNOTATION_GUARDS:
        return _ANNOTATION_GUARDS[key]
    counters = {'blocked_reads': 0, 'guard_installed_before_dependency_loads':
                not any(name in sys.modules for name in ['numpy', 'torch', 'zarr', 'tracksdata'])}

    def audit(event, args):
        if event == 'open' and isinstance(args[0], (str, bytes, os.PathLike)):
            if forbidden_path(args[0], allowed_geff_root):
                counters['blocked_reads'] += 1
                raise PermissionError('Annotations unavailable: ' + os.fsdecode(args[0]))
    sys.addaudithook(audit)
    _ANNOTATION_GUARDS[key] = counters
    return counters


def legacy_associations(ctx):
    """Extract only the pure frozen E teacher decoder, never its OUT globals."""
    import ast
    import collections
    import numpy as np
    from scipy.optimize import linear_sum_assignment
    from .common import adjacency
    path = ctx.repo / 'tools/strong_tracker_v2/decode.py'
    tree = ast.parse(path.read_text())
    body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in {'logit', 'associations'}]
    assert len(body) == 2
    namespace = dict(np=np, defaultdict=collections.defaultdict,
                     linear_sum_assignment=linear_sum_assignment, adjacency=adjacency)
    exec(compile(ast.Module(body=body, type_ignores=[]), str(path), 'exec'), namespace)
    return namespace['associations']


def joint_image_features(sample, graphs):
    """The pinned node-image arithmetic, sharing frame reads across graphs."""
    import numpy as np
    import zarr
    from scipy.ndimage import gaussian_filter
    from annotation_selection.features import FEATURES, frame_features
    from .features import temporal
    from .common import read_json
    path = Path(sample['image_path'])
    meta = read_json(path / 'zarr.json')
    shape = read_json(path / '0/zarr.json')['shape']
    q = float(meta['attributes']['image_statistics']['quantiles']['0.999'])
    assert q > 0
    scale = np.asarray(sample['physical_scale'])
    arr = zarr.open_group(path, mode='r')['0']
    features = [np.zeros((len(nodes), len(FEATURES)), np.float32) for nodes, edges in graphs]
    times = np.unique(np.concatenate([nodes[:, 1] for nodes, _ in graphs]))
    for t in times:
        image = np.asarray(arr[int(t)])
        z, y, x = image.shape
        pooled = image.reshape(z, y//2, 2, x//2, 2).mean(axis=(2, 4), dtype=np.float32)
        spacing = scale * [1, 2, 2]
        responses = []
        for sigma in [1.2, 1.8]:
            background = gaussian_filter(pooled, 2*sigma/spacing, mode='reflect')
            responses.append((gaussian_filter(pooled, sigma/spacing, mode='reflect')-background)/q)
        response = np.maximum(*responses)
        for (nodes, edges), f in zip(graphs, features):
            ids = np.flatnonzero(nodes[:, 1] == t)
            xyz = nodes[ids, 2:].astype(np.int64)
            sample_xyz = np.clip(xyz, 0, np.asarray(image.shape)-1)
            coords = np.clip(xyz//[1, 2, 2], 0, np.asarray(response.shape)-1)
            f[ids] = frame_features(int(t), xyz, response[tuple(coords.T)], image, background,
                                    shape, scale, q, sampling_xyz=sample_xyz)
    for (nodes, edges), f in zip(graphs, features):
        temporal(nodes, edges, f, scale)
    return features


def shared_fresh_heatmaps(ctx, sample, namespace, cache_context):
    """Read only heatmaps generated by this run after their image/model pins match."""
    import numpy as np
    from .common import read_json, sha
    name = sample['dataset']
    root = cache_context.out / 'fresh'
    baseline = root / 'incumbent' / f'{name}.json'
    baseline_record = read_json(baseline)
    assert baseline_record['output_sha256'] == sha(baseline.with_suffix('.npz'))
    assert baseline_record['pipeline_lock_sha256'] == sha(root / 'pipeline_lock.json')
    image_record = read_json(ctx.out / 'input_hashes' / f'{name}.json')
    provenance = dict(image_content_sha256=image_record['image_content_sha256'],
        baseline_receipt_sha256=sha(baseline), pipeline_lock_sha256=sha(root / 'pipeline_lock.json'),
        notebook_sha256=sha(ctx.full / 'harmonic_isolated.py'),
        detector_sha256=sha(Path('/kaggle/input/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt')),
        cache_root=str(root / 'heatmaps' / name), read_map_sha256={}, generated_map_sha256={},
        legacy_heatmap_reads=0)
    original = namespace['deepcenter_heatmap_for_frame']

    def heatmap(dataset, t, detector_bundle, frame_cache, heatmap_cache):
        assert dataset == name
        path = root / 'heatmaps' / name / f'{t}.npy'
        if path.exists():
            result = np.load(path, allow_pickle=False)
            provenance['read_map_sha256'][str(t)] = sha(path)
            namespace['_heatmap_state']['cache_reads'] += 1
            namespace['_heatmap_state']['input_heatmap_hashes'][str(path)] = sha(path)
            return result
        result = original(dataset, t, detector_bundle, frame_cache, heatmap_cache)
        if result is not None:
            provenance['generated_map_sha256'][str(t)] = sha(path)
        return result

    namespace['deepcenter_heatmap_for_frame'] = heatmap
    return provenance


def rebuild_teachers(ctx, sample, raw, pre_ilp, *, source_model, image_dir=None, current_graph=None,
                     fresh_cache_context=None):
    """Recreate old-final and frozen E teacher votes entirely from fresh evidence."""
    import joblib
    import numpy as np
    from .association_fresh import native_v2
    from .features import node_image_features
    from .replay import apply_repair, repair_namespace
    from .common import read_json, sha
    namespace = repair_namespace(fresh_cache_context or ctx, settings={'OUTPUT_MOTION_RELINK': True},
                                 image_dir=image_dir, fresh_heatmaps=True)
    shared = (shared_fresh_heatmaps(ctx, sample, namespace, fresh_cache_context)
              if fresh_cache_context is not None else None)
    old_final, stats = apply_repair(namespace, raw, sample['dataset'], sample['image_shape'])
    if current_graph is None:
        features, _ = node_image_features(ctx, sample, old_final['nodes'], old_final['edges'])
        current_features = None
    else:
        features, current_features = joint_image_features(sample, [
            (old_final['nodes'], old_final['edges']), current_graph])
    native = native_v2(old_final['nodes'], old_final['edges'], features, raw['nodes'], pre_ilp, sample['physical_scale'])
    nf = native['edge_features']
    probability = np.where(nf[:, 1] == 0, nf[:, 0], 1 / (1 + np.exp(nf[:, 6] - 3.)))
    decode = legacy_associations(ctx)
    e_native = decode(old_final['nodes'], old_final['edges'], native, probability, 1.5)
    path = ctx.v2 / 'models' / source_model / 'E_hgb.joblib'
    lock = read_json(ctx.v2 / 'model_lock.json')
    assert sha(path) == lock['models'][str(path.relative_to(ctx.v2))]
    model = joblib.load(path)
    probability = model['model'].predict_proba(nf[:, model['columns']])[:, 1]
    e_hgb = decode(old_final['nodes'], old_final['edges'], native, probability, 1.5)
    provenance = dict(old_repair_stats=stats,
        teacher_model_sha256=sha(path), teacher_decoder_sha256=sha(ctx.repo / 'tools/strong_tracker_v2/decode.py'),
        source_model=source_model, fresh_teachers=True, shared_fresh_heatmaps=shared)
    if current_features is not None:
        provenance['_joint_current_features'] = current_features
    return old_final, e_native, e_hgb, provenance


def apply_policy(ctx, sample, nodes, edges, raw, pre_ilp, policy, *, source_model):
    """Label-free selected V3 API with explicit fresh native inputs and source fit.

    The source model is a declared input, so unknown deployment clips do not
    silently select a policy from a filename. Opposite-embryo studies pass their
    predeclared source model explicitly.
    """
    import numpy as np
    from .common import validate
    unknown = set(policy) - {'association', 'division', 'rescue', 'repair_settings'}
    if unknown:
        raise ValueError(f'Unknown selected policy fields: {sorted(unknown)}')
    if policy.get('rescue'):
        raise NotImplementedError('Selected R policy requires its explicit fresh-input adapter')
    repair_receipt = None
    if policy.get('repair_settings'):
        from .replay import apply_repair, repair_namespace
        namespace = repair_namespace(ctx, settings=policy['repair_settings'],
            image_dir=Path(sample['image_path']).parent, fresh_heatmaps=True)
        graph, repair_receipt = apply_repair(namespace, raw, sample['dataset'], sample['image_shape'])
        nodes, edges = graph['nodes'], graph['edges']
    association = policy.get('association')
    division = policy.get('division')
    if not association and not division:
        validate(nodes, edges, sample['image_shape'])
        return nodes, edges, dict(no_op=repair_receipt is None, source_model=source_model,
                                  conditional_repair=repair_receipt)
    from .association_fresh import build_from_inputs
    from .association import score_features, decode as association_decode
    old, en, eh, provenance = rebuild_teachers(ctx, sample, raw, pre_ilp, source_model=source_model,
        image_dir=Path(sample['image_path']).parent, current_graph=(nodes, edges))
    current_features = provenance.pop('_joint_current_features')
    c, features_receipt = build_from_inputs(ctx, sample, nodes, edges, raw, pre_ilp, old, en, eh,
                                          node_features=current_features)
    ledger = dict(source_model=source_model, teacher_provenance=provenance, features=features_receipt,
                  conditional_repair=repair_receipt)
    if association:
        scores = score_features(ctx, source_model, c, association['model'])
        edges, ledger['association'] = association_decode(nodes, edges, c, scores, association['margin'])
        # Recompute every adjacency-derived feature after association decisions.
        c, ledger['post_association_features'] = build_from_inputs(
            ctx, sample, nodes, edges, raw, pre_ilp, old, en, eh, node_features=c['node_features'])
    if division:
        import zarr
        from .common import read_json, sha
        from .event_proposals import build, extract_crops, ProposalConfig
        from .event_model import predict_logistic, load_image, predict_image
        from .decode import divisions
        event_config = read_json(ctx.out / 'event_inference_config.json')
        pool = event_config['source_pools'][source_model]
        assert division.get('source_pools', {}).get(source_model, pool) == pool
        proposal_config = ProposalConfig(**event_config['proposal_configs'][pool])
        h, ledger['division_proposals'] = build(nodes, edges, c, sample['physical_scale'], proposal_config)
        model_kind = division['model']
        if model_kind == 'image':
            model_kind = f"image_{division.get('seed', 20260909)}"
        model_key = f'{source_model}_{model_kind}'
        assert model_key in event_config['model_sha256'], 'Unknown frozen division model'
        model_name = model_key + ('.joblib' if model_kind == 'logistic' else '.pt')
        model_path = ctx.out / 'event_models' / model_name
        model_record = read_json(model_path.with_suffix('.json'))
        assert sha(model_path) == model_record['model_sha256'], 'Selected division model changed'
        assert sha(model_path) == event_config['model_sha256'][model_key]
        ledger['division_model_sha256'] = model_record['model_sha256']
        if division['model'] == 'logistic':
            probability = predict_logistic(model_path, h['event_features'])
        else:
            crops = extract_crops(zarr.open_group(sample['image_path'], mode='r')['0'], nodes,
                                  h['crop_parents'], sample['physical_scale'])
            image_model = load_image(model_path)
            probability = predict_image(image_model, h['event_features'], crops, h['crop_index'])
        edges, receipt, actions = divisions(nodes, edges, h, probability, c, sample['physical_scale'],
            threshold=division['threshold'], existing_only=division.get('existing_only', False),
            replace=division.get('replace', False))
        ledger['division'] = dict(receipt=receipt, actions=actions)
    validate(nodes, edges, sample['image_shape'])
    return nodes, edges, ledger


def predict_directory(args):
    """Run the delivered policy on an image directory without cached graphs."""
    startup_guards = list(_ANNOTATION_GUARDS.values())
    assert startup_guards and all(g['guard_installed_before_dependency_loads'] for g in startup_guards)
    import csv
    import json
    import shutil
    from .context import RunContext
    from .common import digest, load_graph, read_json, save_arrays, sha, validate, write_json
    from .fresh import prepare, worker
    images = Path(args.images).resolve()
    output = Path(args.output).resolve()
    package = Path(args.package).resolve()
    image_paths = sorted(images.glob('*.zarr'))
    for protected in [images, Path(args.v1).resolve(), Path(args.v2).resolve(), package,
                      *[p.resolve() for p in image_paths]]:
        if output == protected or output.is_relative_to(protected) or protected.is_relative_to(output):
            raise ValueError(f'Output overlaps protected inference input: {protected}')
    manifest = read_json(package / 'manifest.json')
    for relative, expected in manifest['package_files'].items():
        assert sha(package / relative) == expected, f'Package artifact changed: {relative}'
    full = Path(args.v1) / 'public_harmonic_full'
    dependencies = {
        'notebook_sha256': full / 'harmonic_isolated.py',
        'primary_weights_sha256': full / 'tracking_repo/weights/unet_transformer/split_0/edge_predictor_best.pth',
        'secondary_weights_sha256': full / 'secondary_seed_weights/unet_transformer/split_0/edge_predictor_best.pth',
        'deepcenter_weights_sha256': Path('/kaggle/input/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt')}
    for key, path in dependencies.items():
        assert sha(path) == manifest[key], f'External dependency changed: {path}'
    for relative, expected in manifest['tracking_source_files'].items():
        assert sha(full / 'tracking_repo' / relative) == expected, f'Tracking source changed: {relative}'
    for source, expected in manifest['legacy_teacher_model_hashes'].items():
        assert sha(Path(args.v2) / 'models' / source / 'E_hgb.joblib') == expected
    policy = read_json(package / 'policy.json')
    input_view = output / 'image_inputs' / 'train'
    input_view.mkdir(parents=True, exist_ok=True)
    rows = []
    for image in image_paths:
        metadata = read_json(image / 'zarr.json')
        shape = read_json(image / '0/zarr.json')['shape']
        transform = metadata['attributes']['multiscales'][0]['datasets'][0]['coordinateTransformations'][0]
        assert transform['type'] == 'scale'
        target = input_view / image.name
        if not target.exists():
            target.symlink_to(image, target_is_directory=True)
        real_image = image.resolve()
        image_hashes = {str(p.relative_to(real_image)):sha(p) for p in sorted(real_image.rglob('*')) if p.is_file()}
        rows.append(dict(dataset=image.stem, embryo='unseen', image_path=str(target),
            image_shape=shape, physical_scale=transform['scale'][-3:], metadata_hash=sha(image / 'zarr.json'),
            image_content_sha256=digest(image_hashes)))
    if not rows:
        raise ValueError('No image Zarr groups found')
    ctx = RunContext.default(repo=package, data=input_view.parent, v1=args.v1, v2=args.v2,
                             out=output, work=output / 'scratch', official=package / 'unused_metric')
    # This data path is our newly created symlink view inside the output root.
    # Actual image/model/package roots were checked for overlap before any writes.
    write_json(output / 'inputs.json', rows, immutable=True)
    for folder in ['association_models', 'event_models']:
        source, target = package / folder, output / folder
        if source.exists() and not target.exists():
            target.symlink_to(source, target_is_directory=True)
    for name in ['association_model_lock.json', 'association_config.json', 'event_inference_config.json']:
        if (package / name).exists():
            shutil.copyfile(package / name, output / name)
    prepare(ctx, rows, resumable=True)
    worker(ctx)
    columns = ['id', 'dataset', 'row_type', 'node_id', 't', 'z', 'y', 'x', 'source_id', 'target_id']
    node_keys = ['node_id', 't', 'z', 'y', 'x']
    graph_receipts = []
    with (output / 'submission.csv').open('w', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        index = 0
        for row in rows:
            name = row['dataset']
            baseline = load_graph(output / 'fresh/incumbent' / f'{name}.npz')
            raw = load_graph(output / 'fresh/raw' / f'{name}.npz')
            pre = load_graph(output / 'fresh/inputs' / f'pre_ilp_{name}.npz')
            n, e, ledger = apply_policy(ctx, row, baseline['nodes'], baseline['edges'], raw, pre, policy,
                                       source_model=args.source_model)
            save_arrays(output / 'predictions' / f'{name}.npz', nodes=n, edges=e)
            write_json(output / 'prediction_ledgers' / f'{name}.json', ledger)
            graph_receipts.append(dict(dataset=name, **validate(n, e, row['image_shape'])))
            for node in n:
                writer.writerow(dict(id=index, dataset=name, row_type='node', **dict(zip(node_keys, map(int, node)))))
                index += 1
            for a, b in e:
                writer.writerow(dict(id=index, dataset=name, row_type='edge', source_id=int(a), target_id=int(b)))
                index += 1
    module_paths = {name:str(Path(module.__file__).resolve()) for name, module in sys.modules.items()
        if name.startswith(('strong_tracker_v3', 'annotation_selection')) and getattr(module, '__file__', None)}
    assert all(Path(path).is_relative_to(package / 'tools') for path in module_paths.values())
    assert Path(__file__).resolve().is_relative_to(package / 'tools')
    assert not any(g['blocked_reads'] for g in startup_guards)
    write_json(output / 'inference_receipt.json', dict(samples=len(rows), graphs=graph_receipts,
        source_model=args.source_model, policy=policy, annotation_reads=0, cached_graph_inputs=False,
        annotations_unavailable_from_start=True, guard_installed_before_dependency_loads=True,
        inference_module_path=str(Path(__file__).resolve()), module_paths=module_paths,
        source_modules_within_package=True, package_manifest_sha256=sha(package / 'manifest.json'),
        image_content_hashes={row['dataset']:row['image_content_sha256'] for row in rows},
        submission_sha256=sha(output / 'submission.csv')))


def stream_fresh_repairs(ctx):
    """Overlap fresh repairs with neural shards using fingerprinted new outputs.

    The shard CLI later verifies and reuses these exact per-clip completion
    receipts. Four outstanding neural clips provide a conservative separation
    before handing the remaining repairs back to each original worker.
    """
    import shutil
    import time
    from dataclasses import replace
    from .common import graph_hash, load_graph, read_json, save_arrays, sha, validate, write_json
    from .replay import apply_repair, repair_namespace
    shards = [replace(ctx, out=p) for p in sorted((ctx.out / 'fresh_full').glob('shard*')) if p.is_dir()]
    if not shards:
        raise ValueError('No fresh neural shards are running')
    completed, handed_back = [], set()
    while len(handed_back) < len(shards):
        made_progress = False
        for part in shards:
            if str(part.out) in handed_back:
                continue
            config = read_json(part.out / 'fresh/pipeline_lock.json')
            samples = part.samples()
            ready = list((part.out / 'fresh/raw_checkpoints').glob('*.json'))
            if len(samples) - len(ready) <= 4:
                handed_back.add(str(part.out))
                continue
            for sample in samples:
                name = sample['dataset']
                raw_path = part.out / 'fresh/raw_checkpoints' / f'{name}.npz'
                raw_receipt = raw_path.with_suffix('.json')
                final_path = part.out / 'fresh/incumbent' / f'{name}.npz'
                final_receipt = final_path.with_suffix('.json')
                if not raw_receipt.exists() or final_receipt.exists():
                    continue
                source = read_json(raw_receipt)
                assert source['pipeline_fingerprint'] == config['settings']['V3_PIPELINE_FINGERPRINT']
                assert source['sha256'] == sha(raw_path)
                raw = load_graph(raw_path)
                raw_copy = part.out / 'fresh/raw' / f'{name}.npz'
                raw_copy.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(raw_path, raw_copy)
                start = time.perf_counter()
                namespace = repair_namespace(part, image_dir=config['image_dir'], fresh_heatmaps=True)
                graph, stats = apply_repair(namespace, raw, name, sample['image_shape'])
                save_arrays(final_path, nodes=graph['nodes'], edges=graph['edges'])
                receipt = dict(dataset=name, repair_seconds=time.perf_counter()-start,
                    graph_hash=graph_hash(graph['nodes'], graph['edges']), stats=stats,
                    validity=validate(graph['nodes'], graph['edges'], sample['image_shape']),
                    output_sha256=sha(final_path), pipeline_lock_sha256=sha(part.out / 'fresh/pipeline_lock.json'),
                    fresh_heatmap_queries=namespace['_heatmap_state']['fresh_heatmaps'])
                write_json(final_receipt, receipt)
                completed.append(dict(dataset=name, shard=str(part.out), **{'seconds': receipt['repair_seconds']}))
                made_progress = True
                print('Streaming fresh repair', len(completed), name, receipt['repair_seconds'], flush=True)
                break
        if not made_progress and len(handed_back) < len(shards):
            time.sleep(10)
    write_json(ctx.out / 'stream_fresh_repair_receipt.json', dict(completed=completed,
        annotation_reads=0, old_graph_reads=0, handoff_to_original_workers=list(handed_back)))


def precision_audit(ctx, *, full=False, require_complete=False):
    """Comparison-only exact raw/native audit, never an inference input."""
    import numpy as np
    from .common import load_graph, read_json, sha, write_json

    def compare(old_path, new_path, keys):
        old, new = load_graph(old_path), load_graph(new_path)
        result = dict(old_sha256=sha(old_path), fresh_sha256=sha(new_path), fields={})
        for key in keys:
            a, b = old[key], new[key]
            same_shape = a.shape == b.shape
            entry = dict(exact_array_equal=np.array_equal(a, b), shape_old=list(a.shape), shape_fresh=list(b.shape),
                         dtype_old=str(a.dtype), dtype_fresh=str(b.dtype), same_shape=same_shape,
                         exact_bytes_equal=same_shape and a.dtype == b.dtype and a.tobytes() == b.tobytes())
            if same_shape and np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number):
                aa, bb = a.astype(np.float64), b.astype(np.float64)
                finite = np.isfinite(aa) & np.isfinite(bb)
                entry['max_abs_difference'] = float(np.max(np.abs(aa[finite]-bb[finite]))) if finite.any() else 0.
                entry['different_elements'] = int(np.sum(a != b))
                entry['nonfinite_mask_equal'] = np.array_equal(np.isfinite(aa), np.isfinite(bb))
            else:
                entry['max_abs_difference'] = None
            result['fields'][key] = entry
        return result

    rows = []
    if full:
        candidates = [(p['dataset'], shard / 'fresh/raw_checkpoints' / f"{p['dataset']}.npz",
                       shard / 'fresh/inputs' / f"pre_ilp_{p['dataset']}.npz")
                      for shard in sorted((ctx.out / 'fresh_full').glob('shard*'))
                      for p in read_json(shard / 'inputs.json')]
    else:
        candidates = [(p['dataset'], ctx.out / 'fresh/raw' / f"{p['dataset']}.npz",
                       ctx.out / 'fresh/inputs' / f"pre_ilp_{p['dataset']}.npz")
                      for p in read_json(ctx.out / 'fresh_pilot_lock.json')['selected']]
    for name, raw, pre in candidates:
        # A raw checkpoint receipt is the completed-write boundary for full runs.
        if not raw.exists() or not pre.exists() or (full and not raw.with_suffix('.json').exists()):
            continue
        rows.append(dict(dataset=name,
            raw=compare(ctx.v2 / 'raw' / f'{name}.npz', raw, ['nodes', 'edges', 'edge_prob']),
            pre_ilp=compare(ctx.full / 'inputs' / f'pre_ilp_{name}.npz', pre,
                            ['coords', 'node_probabilities', 'edge_scores'])))
    if require_complete:
        assert len(rows) == len(candidates), 'Fresh precision audit missing expected clips'
    summary = dict(expected_samples=len(candidates), completed_samples=len(rows),
        comparison_only=True, used_for_prediction=False,
        all_raw_fields_exact=all(all(f['exact_array_equal'] for f in r['raw']['fields'].values()) for r in rows),
        all_pre_ilp_fields_exact=all(all(f['exact_array_equal'] for f in r['pre_ilp']['fields'].values()) for r in rows),
        differing_datasets=[r['dataset'] for r in rows if any(not f['exact_array_equal']
            for group in ['raw', 'pre_ilp'] for f in r[group]['fields'].values())], rows=rows)
    write_json(ctx.out / ('fresh_full_precision_audit.json' if full else 'fresh_pilot_precision_audit.json'), summary)
    return summary


def benchmark_startup(ctx):
    """New-process dependency/model startup on the already-warmed local disk."""
    import time
    import importlib.util
    start = time.perf_counter()
    from .common import read_json, sha, write_json
    import torch
    config = read_json(ctx.out / 'fresh/pipeline_lock.json')
    source = Path(config['source_repo'])
    sys.path[:0] = [str(source / 'src'), str(source / 'scripts')]
    spec = importlib.util.spec_from_file_location('v3_startup_predictor', source / 'scripts/predict_unet_transformer.py')
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    imports_done = time.perf_counter()
    assert torch.cuda.is_available()
    torch.cuda.init()
    torch.cuda.synchronize()
    cuda_done = time.perf_counter()
    primary = source / 'weights/unet_transformer/split_0/edge_predictor_best.pth'
    secondary = Path(config['settings']['BIOHUB_SECONDARY_WEIGHTS'])
    for path in [primary, secondary]:
        module.load_model(path, torch.device('cuda'))
    torch.cuda.synchronize()
    end = time.perf_counter()
    receipt = dict(dependency_import_seconds=imports_done-start, cuda_initialization_seconds=cuda_done-imports_done,
        primary_secondary_load_seconds=end-cuda_done, total_seconds=end-start,
        filesystem_cache='warm from executed pilots/full run; no cold-cache claim',
        annotation_reads=0, startup_guard=True, model_hashes={str(p):sha(p) for p in [primary,secondary]},
        cuda_peak_bytes=torch.cuda.max_memory_allocated())
    write_json(ctx.out / 'fresh_startup_benchmark.json', receipt)
    return receipt


def validate_fresh_inputs(ctx):
    """Bind fresh pipeline receipts to the full image-content hash manifest."""
    from .common import digest, now, read_json, sha, write_json
    manifest_path = ctx.out / 'label_free_input_hash_manifest.json'
    manifest = read_json(manifest_path)
    count = 0
    for sample in ctx.samples():
        name = sample['dataset']
        root = Path(sample['image_path'])
        record = read_json(ctx.out / 'input_hashes' / f'{name}.json')
        actual = {str(p.relative_to(root)): [p.stat().st_size, p.stat().st_mtime_ns]
                  for p in root.rglob('*') if p.is_file()}
        assert actual == record['file_stats'], f'Raw image file tree changed: {name}'
        assert record['image_content_sha256'] == manifest['inputs'][name]['image_content_sha256']
        assert sha(root / 'zarr.json') == record['files']['zarr.json']
        assert sha(root / '0/zarr.json') == record['files']['0/zarr.json']
        count += len(actual)
    pipelines = {str(p.relative_to(ctx.out)): sha(p)
                 for p in sorted((ctx.out / 'fresh_full').glob('*/fresh/pipeline_lock.json'))}
    receipt = dict(created=now(), samples=len(ctx.samples()), image_files=count,
        whole_content_manifest_sha256=sha(manifest_path), pipeline_locks=pipelines,
        joint_resume_fingerprint=digest(dict(image_manifest=sha(manifest_path), pipelines=pipelines)),
        raw_image_stats_and_metadata_unchanged=True,
        scope='Full image bytes were hashed in the original manifest; this read-only validation rejects changed size/mtime, metadata, added or missing files before reuse')
    write_json(ctx.out / 'fresh_input_resume_validation.json', receipt)
    return receipt


def fresh_evidence_one(task):
    ctx, sample, shard = task
    deny_annotations()
    import ast
    import time
    import numpy as np
    from dataclasses import replace
    from .common import digest, graph_hash, load_graph, read_json, save_arrays, sha, write_json
    from .association_fresh import build_from_inputs
    from .association import decode, score_features
    name = sample['dataset']
    source_model = '6bba' if sample['embryo'] == '44b6' else '44b6'
    raw_path = shard / 'fresh/raw_checkpoints' / f'{name}.npz'
    pre_path = shard / 'fresh/inputs' / f'pre_ilp_{name}.npz'
    base_path = shard / 'fresh/incumbent' / f'{name}.npz'
    relevant = {'legacy_associations', 'joint_image_features', 'shared_fresh_heatmaps',
                'rebuild_teachers', 'fresh_evidence_one'}
    tree = ast.parse(Path(__file__).read_text())
    code = digest([ast.dump(n, include_attributes=False) for n in tree.body
                   if isinstance(n, ast.FunctionDef) and n.name in relevant])
    inputs = dict(raw_sha256=sha(raw_path), pre_ilp_sha256=sha(pre_path), baseline_sha256=sha(base_path),
        image_content_sha256=read_json(ctx.out / 'input_hashes' / f'{name}.json')['image_content_sha256'],
        teacher_model_sha256=sha(ctx.v2 / 'models' / source_model / 'E_hgb.joblib'),
        association_model_lock_sha256=sha(ctx.out / 'association_model_lock.json'),
        evidence_functions_sha256=code,
        code_files={k:sha(ctx.repo / 'tools/strong_tracker_v3' / k)
                    for k in ['association_fresh.py', 'features.py', 'disagreements.py', 'replay.py', 'association.py']})
    target = ctx.out / 'fresh_evidence' / f'{name}.npz'
    receipt_path = target.with_suffix('.json')
    if receipt_path.exists():
        receipt = read_json(receipt_path)
        assert receipt['inputs'] == inputs and receipt['sha256'] == sha(target), 'Stale fresh evidence'
        assert all(sha(ctx.out / p) == h for p, h in receipt['predictions'].items())
        return dict(dataset=name, resumed=True)
    start = time.perf_counter()
    raw, pre, base = load_graph(raw_path), load_graph(pre_path), load_graph(base_path)
    assert read_json(base_path.with_suffix('.json'))['output_sha256'] == sha(base_path)
    old, en, eh, provenance = rebuild_teachers(ctx, sample, raw, pre, source_model=source_model,
        image_dir=shard / 'fresh/inputs/test', current_graph=(base['nodes'], base['edges']),
        fresh_cache_context=replace(ctx, out=shard))
    node_features = provenance.pop('_joint_current_features')
    native, meta = build_from_inputs(ctx, sample, base['nodes'], base['edges'], raw, pre,
                                    old, en, eh, node_features=node_features)
    save_arrays(target, **native, old_nodes=old['nodes'], old_edges=old['edges'],
                e_native=en, e_hgb=eh, incumbent_nodes=base['nodes'], incumbent_edges=base['edges'])
    scores = score_features(ctx, source_model, native, 'residual')
    predictions, comparisons = {}, {}
    for margin in [1.5, 3.0]:
        variant = f'A_residual_m{margin}'
        edges, ledger = decode(base['nodes'], base['edges'], native, scores, margin)
        output = ctx.out / 'fresh_candidates' / variant / f'{name}.npz'
        save_arrays(output, nodes=base['nodes'], edges=edges)
        predictions[str(output.relative_to(ctx.out))] = sha(output)
        write_json(ctx.out / 'fresh_prediction_ledgers' / variant / f'{name}.json', ledger)
        # Comparison occurs only after independently saving the new prediction.
        expected = load_graph(ctx.out / 'candidate_graphs' / variant / f'{name}.npz')
        comparisons[variant] = graph_hash(base['nodes'], edges) == graph_hash(expected['nodes'], expected['edges'])
    archived = ctx.out / 'source_snapshots/evidence_pre_shared_heatmaps/fresh_evidence' / target.name
    optimization_parity = None
    if archived.exists():
        previous, current = load_graph(archived), load_graph(target)
        optimization_parity = set(previous) == set(current) and all(
            previous[key].dtype == current[key].dtype and previous[key].shape == current[key].shape
            and previous[key].tobytes() == current[key].tobytes() for key in previous)
        assert optimization_parity, 'Shared fresh heatmaps changed evidence arrays'
    receipt = dict(dataset=name, source_model=source_model, inputs=inputs, sha256=sha(target),
        raw_path=str(raw_path), pre_ilp_path=str(pre_path), baseline_path=str(base_path),
        seconds=time.perf_counter()-start, predictions=predictions, cache_graph_comparison=comparisons,
        cached_graph_reads_for_prediction=0, annotation_reads=0, teacher_provenance=provenance,
        features=meta, joint_image_features=True, shared_heatmap_optimization_exact_array_parity=optimization_parity)
    write_json(receipt_path, receipt)
    return dict(dataset=name, seconds=receipt['seconds'], comparisons=comparisons)


def stream_fresh_evidence(ctx, workers=2):
    """Consume newly completed fresh graphs while neural inference continues."""
    import multiprocessing as mp
    import time
    from concurrent.futures import ProcessPoolExecutor, wait, FIRST_COMPLETED
    from .common import read_json, write_json
    tasks = []
    for shard in sorted((ctx.out / 'fresh_full').glob('shard*')):
        tasks.extend((ctx, sample, shard) for sample in read_json(shard / 'inputs.json'))
    ordering = {sample['dataset']: i for i, sample in enumerate(ctx.samples())}
    tasks.sort(key=lambda task: ordering[task[1]['dataset']])
    assert len(tasks) == 199
    pending = list(tasks)
    done = []
    with ProcessPoolExecutor(max_workers=workers, mp_context=mp.get_context('spawn')) as pool:
        futures = {}
        while pending or futures:
            for task in list(pending):
                if len(futures) >= workers:
                    break
                _, sample, shard = task
                path = shard / 'fresh/incumbent' / f"{sample['dataset']}.json"
                if path.exists():
                    futures[pool.submit(fresh_evidence_one, task)] = task
                    pending.remove(task)
            if not futures:
                time.sleep(10)
                continue
            completed, _ = wait(futures, timeout=10, return_when=FIRST_COMPLETED)
            for future in completed:
                result = future.result()
                done.append(result)
                del futures[future]
                print('Fresh evidence', len(done), '/199', result, flush=True)
    write_json(ctx.out / 'fresh_evidence_receipt.json', dict(samples=len(done), records=done,
        annotation_reads=0, fresh_image_native_teacher_features=True))


def summarize_fresh_delivery(ctx, variant):
    """Concise measured receipt; detailed per-clip evidence stays in local artifacts."""
    import json
    import numpy as np
    from .common import graph_hash, load_graph, read_json, sha, write_json
    names = {sample['dataset'] for sample in ctx.samples()}
    assert len(names) == 199
    full = read_json(ctx.out / 'fresh_full_receipt.json')
    precision = read_json(ctx.out / 'fresh_full_precision_audit.json')
    assert full['samples'] == precision['completed_samples'] == 199
    evidence = [read_json(ctx.out / 'fresh_evidence' / f'{name}.json') for name in sorted(names)]
    actual = {p.stem for p in (ctx.out / 'fresh_candidates' / variant).glob('*.npz')}
    assert actual == names, 'Fresh selected graph coverage differs from the expected set'
    selected_equal = 0
    for name in sorted(names):
        fresh = load_graph(ctx.out / 'fresh_candidates' / variant / f'{name}.npz')
        cached = load_graph(ctx.out / 'candidate_graphs' / variant / f'{name}.npz')
        selected_equal += graph_hash(fresh['nodes'], fresh['edges']) == graph_hash(cached['nodes'], cached['edges'])
    timings = [json.loads(line) for path in (ctx.out / 'fresh_full').glob('*/fresh/neural_timings.jsonl')
               for line in path.read_text().splitlines()]
    assert {r['dataset'] for r in timings} == names and len(timings) == 199

    def distribution(values):
        a = np.asarray(values)
        return dict(sum=float(a.sum()), median=float(np.median(a)), p90=float(np.quantile(a, .9)), max=float(a.max()))

    artifacts = ['fresh_full_receipt.json', 'fresh_full_precision_audit.json',
        'fresh_input_resume_validation.json', 'fresh_evidence_receipt.json',
        'fresh_startup_benchmark.json', 'fresh_teacher_pilots_receipt.json',
        'fresh_association_m3_pilots_receipt.json', 'fresh_heatmap_storage_dedup.json',
        'fresh_heatmap_optimization_parity.json', 'fresh_teacher_native_parity_summary.json',
        'fresh_numeric_validation_receipt.json', 'package_smoke_receipt.json']
    receipt = dict(status='full_fresh_selected_complete', samples=199, variant=variant,
        full_neural_wall_seconds=full['wall_seconds'], fresh_selected_graphs_equal_to_scored=selected_equal,
        exact_raw_array_parity=precision['all_raw_fields_exact'],
        exact_pre_ilp_array_parity=precision['all_pre_ilp_fields_exact'],
        fresh_incumbent_graphs_equal=full['exact_incumbent_parity'],
        neural_io_seconds=distribution([r['neural_io_seconds'] for r in timings]),
        graph_ilp_export_seconds=distribution([r['graph_ilp_export_seconds'] for r in timings]),
        teacher_native_feature_decode_seconds=distribution([r['seconds'] for r in evidence]),
        cuda_peak_allocated_bytes=max(r['cuda_peak_bytes'] for r in timings),
        fresh_evidence_optimization_byte_parity_samples=sum(
            r['shared_heatmap_optimization_exact_array_parity'] is True for r in evidence),
        timing_note='Stage sums overlap across processes; compare wall time separately. Dependency startup measured on a warm filesystem.',
        annotations_unavailable_from_start=True, cached_graph_reads_for_prediction=0,
        kaggle_runtime_proven=False, official_fresh_selected_scoring='Separate independent root evaluator',
        artifacts={relative: sha(ctx.out / relative) for relative in artifacts if (ctx.out / relative).exists()})
    write_json(ctx.out / 'fresh_delivery_receipt.json', receipt)
    return receipt


def fresh_selected_one(task):
    """Apply frozen selected A/D to freshly generated evidence, refreshing after A."""
    ctx, sample, variant, policy = task
    deny_annotations()
    import ast
    import time
    from .common import digest, graph_hash, load_graph, read_json, save_arrays, sha, validate, write_json
    from .association import decode, score_features
    from .association_fresh import build_from_inputs
    if set(policy) - {'association', 'division'}:
        raise NotImplementedError('Fresh selected evidence runner currently supports the measured A/D policies')
    name = sample['dataset']
    source = '6bba' if sample['embryo'] == '44b6' else '44b6'
    path = ctx.out / 'fresh_evidence' / f'{name}.npz'
    while not path.with_suffix('.json').exists():
        time.sleep(10)
    previous = read_json(path.with_suffix('.json'))
    assert sha(path) == previous['sha256']
    code = digest([ast.dump(n, include_attributes=False) for n in ast.parse(Path(__file__).read_text()).body
                   if isinstance(n, ast.FunctionDef) and n.name in {'fresh_selected_one', 'apply_fresh_selected'}])
    inputs = dict(evidence_sha256=sha(path), policy_sha256=digest(policy),
        inference_functions_sha256=code,
        association_model_lock_sha256=sha(ctx.out / 'association_model_lock.json'),
        event_config_sha256=sha(ctx.out / 'event_inference_config.json') if policy.get('division') else None,
        code_files={f:sha(ctx.repo / 'tools/strong_tracker_v3' / f) for f in
            ['association.py', 'association_fresh.py', 'features.py', 'disagreements.py',
             'event_pipeline.py', 'event_model.py', 'event_proposals.py', 'decode.py']})
    output = ctx.out / 'fresh_candidates' / variant / f'{name}.npz'
    receipt_path = ctx.out / 'fresh_selected_ledgers' / variant / f'{name}.json'
    if receipt_path.exists():
        r = read_json(receipt_path)
        assert r['inputs'] == inputs and r['output_sha256'] == sha(output)
        return dict(dataset=name, resumed=True)
    start = time.perf_counter()
    c = load_graph(path)
    raw, pre = load_graph(previous['raw_path']), load_graph(previous['pre_ilp_path'])
    assert sha(previous['raw_path']) == previous['inputs']['raw_sha256']
    assert sha(previous['pre_ilp_path']) == previous['inputs']['pre_ilp_sha256']
    nodes, edges = c['incumbent_nodes'], c['incumbent_edges']
    ledger = dict(source_model=source, fresh_native_features=True, graph_features_recomputed=False)
    association, division = policy.get('association'), policy.get('division')
    if association:
        scores = score_features(ctx, source, c, association['model'])
        edges, ledger['association'] = decode(nodes, edges, c, scores, association['margin'])
        c, ledger['post_association_features'] = build_from_inputs(ctx, sample, nodes, edges,
            raw, pre, dict(nodes=c['old_nodes'], edges=c['old_edges']), c['e_native'], c['e_hgb'],
            node_features=c['node_features'])
        ledger['graph_features_recomputed'] = True
    if division:
        from .event_pipeline import apply
        model = division['model']
        if model == 'image':
            model = f"image_{division.get('seed', 20260909)}"
        nodes, edges, ledger['division'] = apply(ctx, sample, nodes, edges, model=model,
            threshold=division['threshold'], replace=division.get('replace', False),
            existing_only=division.get('existing_only', False), source=source, native=c)
    validate(nodes, edges, sample['image_shape'])
    if output.exists():
        existing = load_graph(output)
        assert graph_hash(existing['nodes'], existing['edges']) == graph_hash(nodes, edges)
    else:
        save_arrays(output, nodes=nodes, edges=edges)
    expected = load_graph(ctx.out / 'candidate_graphs' / variant / f'{name}.npz')
    write_json(receipt_path, dict(dataset=name, inputs=inputs, output_sha256=sha(output),
        graph_hash=graph_hash(nodes, edges), seconds=time.perf_counter()-start, ledger=ledger,
        cached_graph_reads_for_prediction=0, annotation_reads=0,
        scored_graph_equal=graph_hash(nodes, edges) == graph_hash(expected['nodes'], expected['edges'])))
    return dict(dataset=name, seconds=time.perf_counter()-start)


def apply_fresh_selected(ctx, variant, policy, workers=2):
    import ast
    from .common import digest, read_json, run_pool, sha, write_json
    code = digest([ast.dump(n, include_attributes=False) for n in ast.parse(Path(__file__).read_text()).body
                   if isinstance(n, ast.FunctionDef) and n.name in {'fresh_selected_one', 'apply_fresh_selected'}])
    lock = dict(variant=variant, policy=policy, samples=[s['dataset'] for s in ctx.samples()],
        inference_functions_sha256=code, source_only=True, annotation_unavailable=True)
    write_json(ctx.out / 'fresh_selected_policy_lock.json', lock, immutable=True)
    assert len(lock['samples']) == 199
    if hasattr(os, 'sched_getaffinity'):
        os.sched_setaffinity(0, set(sorted(os.sched_getaffinity(0))[:32]))
    list(run_pool(fresh_selected_one, [(ctx, s, variant, policy) for s in ctx.samples()], workers))
    records = [read_json(ctx.out / 'fresh_selected_ledgers' / variant / f'{name}.json') for name in lock['samples']]
    receipt = dict(variant=variant, samples=199, policy_sha256=digest(policy),
        annotations_unavailable_from_start=True, fresh_evidence_inputs=True,
        graph_features_recomputed_after_A=all(r['ledger']['graph_features_recomputed'] for r in records)
            if policy.get('association') else None,
        scored_graphs_equal=sum(r['scored_graph_equal'] for r in records),
        prediction_hashes={r['dataset']:r['output_sha256'] for r in records})
    write_json(ctx.out / 'fresh_selected_inference_receipt.json', receipt)
    return receipt


def teacher_native_parity_audit(ctx, *, require_complete=False):
    """Read-only reconciliation of original, canonical teacher and native evidence."""
    import numpy as np
    from .common import load_graph, read_json, sha, write_json
    rows = []
    bounds_nodes, tie_nodes, unexplained, shifted = 0, 0, 0, []
    for sample in ctx.samples():
        name = sample['dataset']
        path = ctx.out / 'fresh_evidence' / f'{name}.npz'
        if not path.with_suffix('.json').exists():
            continue
        fresh = load_graph(path)
        old = load_graph(ctx.v1 / 'baseline/public' / f'{name}.npz')
        votes = load_graph(ctx.v2 / 'predictions' / f'{name}.npz')
        native = load_graph(ctx.out / 'features' / f'{name}.npz')
        a, b = old['nodes'], fresh['old_nodes']
        identity = a.shape == b.shape and np.array_equal(a[:, :2], b[:, :2])
        row = dict(dataset=name, old_node_identity_exact=identity,
            old_nodes_exact=np.array_equal(a, b), old_edges_exact=np.array_equal(old['edges'], fresh['old_edges']),
            e_native_exact=np.array_equal(votes['E_native_m1.5__edges'], fresh['e_native']),
            e_hgb_exact=np.array_equal(votes['E_hgb_m1.5__edges'], fresh['e_hgb']),
            native_fields_exact={key: np.array_equal(value, fresh[key], equal_nan=True) for key, value in native.items()},
            native_fields_finite={key:bool(np.isfinite(fresh[key]).all()) for key in native},
            coordinate_changes=[])
        if identity and not row['old_nodes_exact']:
            compatibility_path = ctx.v2 / 'replay/identity' / name / 'complete.json'
            compatibility = read_json(compatibility_path).get('numerical_export_compatibility', [])
            tie = {(r['node_id'], r['axis']): r for r in compatibility}
            row['sealed_serializer_receipt_sha256'] = sha(compatibility_path)
            for i in np.flatnonzero(np.any(a[:, 2:] != b[:, 2:], axis=1)):
                causes = []
                for j in np.flatnonzero(a[i] != b[i]):
                    axis = 'id t z y x'.split()[j]
                    limit = sample['image_shape'][j-1]-1
                    key = (int(a[i, 0]), axis)
                    if b[i, j] == np.clip(a[i, j], 0, limit) and not 0 <= a[i, j] <= limit:
                        causes.append('upper_or_lower_bound')
                    elif key in tie and a[i, j] == tie[key]['sealed_integer'] and b[i, j] == tie[key]['native_integer']:
                        assert abs((tie[key]['unrounded'] % 1)-.5) <= 1e-10
                        causes.append('documented_half_integer_serialization')
                    else:
                        causes.append('unexplained')
                distance = float(np.linalg.norm((a[i, 2:]-b[i, 2:]) * sample['physical_scale']))
                shifted.append(distance)
                bounds_nodes += 'upper_or_lower_bound' in causes
                tie_nodes += 'documented_half_integer_serialization' in causes
                unexplained += 'unexplained' in causes
                row['coordinate_changes'].append(dict(node_id=int(a[i, 0]), causes=causes, physical_shift_um=distance))
        rows.append(row)
    if require_complete:
        assert len(rows) == len(ctx.samples()) == 199
    detailed = ctx.out / 'fresh_teacher_native_full_parity_audit.json'
    write_json(detailed, dict(comparison_only=True, samples=len(rows), rows=rows))
    summary = dict(samples=len(rows), expected_samples=len(ctx.samples()), comparison_only=True,
        used_for_prediction=False, old_teacher_node_identity_exact=all(r['old_node_identity_exact'] for r in rows),
        old_teacher_node_arrays_exact_clips=sum(r['old_nodes_exact'] for r in rows),
        old_teacher_coordinate_difference_clips=sum(not r['old_nodes_exact'] for r in rows),
        changed_old_teacher_nodes=len(shifted), bounded_nodes=bounds_nodes,
        documented_half_integer_serialization_nodes=tie_nodes, unexplained_coordinate_changes=unexplained,
        max_old_teacher_physical_shift_um=max(shifted, default=0.),
        all_old_teacher_edges_exact=all(r['old_edges_exact'] for r in rows),
        all_E_native_edges_exact=all(r['e_native_exact'] for r in rows),
        all_E_hgb_edges_exact=all(r['e_hgb_exact'] for r in rows),
        all_current_native_feature_fields_exact=all(all(r['native_fields_exact'].values()) for r in rows),
        all_current_native_numeric_arrays_finite=all(all(r['native_fields_finite'].values()) for r in rows),
        cause='Fresh canonical teacher enforces image bounds and uses native rounding. Original V1 retained six pre-existing out-of-bounds points and two documented ULP half-integer serializer values.',
        detailed_artifact=str(detailed), detailed_sha256=sha(detailed),
        original_report_sha256=sha(ctx.repo / 'results/strong-tracker-v2/v2_report.md'))
    write_json(ctx.out / 'fresh_teacher_native_parity_summary.json', summary)
    return summary


def prepare_export_attestation(ctx, variant):
    """Evaluation-only process: export only graph hashes, never scores or counts."""
    import csv
    from .common import sha, write_json
    if _ANNOTATION_GUARDS:
        raise RuntimeError('Build the score attestation in a separate evaluation-only process')
    source = ctx.out / 'score_rows.csv'
    source_hash = sha(source)
    score_variant = 'incumbent' if variant in {'incumbent', 'bypass_motion_bounds'} else variant
    with source.open(newline='') as handle:
        selected = [{key:row[key] for key in ['dataset', 'graph_file_sha256', 'scorer_hash']}
                    for row in csv.DictReader(handle) if row['variant'] == score_variant]
    assert sha(source) == source_hash, 'Official score rows changed while binding export hashes'
    names = {s['dataset'] for s in ctx.samples()}
    assert len(selected) == len(names) == 199 and {r['dataset'] for r in selected} == names
    record = dict(variant=variant, score_variant=score_variant,
        official_score_rows_sha256=source_hash, metric_revision=ctx.metric_revision,
        scorer_hashes=sorted({r['scorer_hash'] for r in selected}),
        graph_file_sha256={r['dataset']:r['graph_file_sha256'] for r in selected},
        evaluation_only_attestation=True, annotations_or_scores_included=False)
    write_json(ctx.out / 'export_scoring_manifest.json', record)
    return record


def package_smoke(ctx, variant):
    """Execute the copied package twice from images and validate its emitted CSVs."""
    import shutil
    import subprocess
    import time
    import numpy as np
    import pandas as pd
    from .common import graph_hash, load_graph, read_json, sha, validate, write_json
    package = ctx.out / 'inference_package'
    manifest = read_json(package / 'manifest.json')
    assert manifest['variant'] == variant
    assert read_json(ctx.out / 'selected_prediction_lock.json')['variant'] == variant
    manifest_hash = sha(package / 'manifest.json')
    root = ctx.out / 'package_smoke' / f'{variant}_{manifest_hash[:12]}'
    copied = root / 'copied_package'
    if not copied.exists():
        shutil.copytree(package, copied)
    assert sha(copied / 'manifest.json') == manifest_hash
    assert all(sha(copied / relative) == expected for relative, expected in manifest['package_files'].items())
    cwd = root / 'outside_repository_cwd'
    cwd.mkdir(parents=True, exist_ok=True)
    assert not cwd.resolve().is_relative_to(ctx.repo.resolve())
    attempt = 1
    while (root / 'attempts' / f'{attempt:03d}').exists():
        attempt += 1
    attempt_root = root / 'attempts' / f'{attempt:03d}'
    attempt_root.mkdir(parents=True)
    pilots = read_json(ctx.out / 'fresh_pilot_lock.json')['selected']
    assert {r['dataset'] for r in pilots} == {'44b6_87bba6c4', '6bba_789f8168'}
    samples = {r['dataset']:r for r in ctx.samples()}
    records = []
    def one(pilot):
        name = pilot['dataset']
        sample = samples[name]
        source = '6bba' if sample['embryo'] == '44b6' else '44b6'
        images = root / 'pilot_images' / name
        images.mkdir(parents=True, exist_ok=True)
        image_link = images / f'{name}.zarr'
        if not image_link.exists():
            image_link.symlink_to(Path(sample['image_path']).resolve(), target_is_directory=True)
        output = attempt_root / 'outputs' / name
        assert not output.exists(), 'Copied-package smoke must start without prediction checkpoints'
        command = [str(copied / 'run.sh'), '--python', sys.executable, '--images', str(images),
            '--output', str(output), '--v1', str(ctx.v1), '--v2', str(ctx.v2), '--source-model', source]
        start = time.perf_counter()
        log_path = attempt_root / f'{name}.log'
        with log_path.open('w') as log:
            process = subprocess.run(command, cwd=cwd, stdout=log, stderr=subprocess.STDOUT, check=False)
        record = dict(dataset=name, source_model=source, returncode=process.returncode,
            seconds=time.perf_counter()-start, command=command, cwd_outside_repository=True,
            output_was_absent_at_launch=True,
            log_sha256=sha(log_path), log_path=str(log_path))
        if process.returncode:
            return record
        inference_path = output / 'inference_receipt.json'
        worker_path = output / 'fresh/worker_receipt.json'
        inf, worker = read_json(inference_path), read_json(worker_path)
        assert inf['source_model'] == source and inf['package_manifest_sha256'] == manifest_hash
        assert inf['annotations_unavailable_from_start'] and inf['guard_installed_before_dependency_loads']
        assert inf['annotation_reads'] == worker['annotation_reads'] == 0
        assert worker['startup_guard'] and worker['completed'] and worker['fresh_image_neural_inference']
        assert worker['graph_cache_reads_for_prediction'] == 0 and not inf['cached_graph_inputs']
        module_paths = list(inf['module_paths'].values()) + [inf['inference_module_path']]
        assert all(Path(path).resolve().is_relative_to(copied / 'tools') for path in module_paths)
        prediction = load_graph(output / 'predictions' / f'{name}.npz')
        expected = load_graph(ctx.out / 'selected_predictions' / f'{name}.npz')
        selected_equal = graph_hash(prediction['nodes'], prediction['edges']) == graph_hash(expected['nodes'], expected['edges'])
        csv_path = output / 'submission.csv'
        frame = pd.read_csv(csv_path)
        assert set(frame['dataset']) == {name} and frame['row_type'].isin(['node', 'edge']).all()
        assert frame['id'].tolist() == list(range(len(frame)))
        nodes = frame.loc[frame.row_type == 'node', ['node_id', 't', 'z', 'y', 'x']].to_numpy(np.int64)
        edges = frame.loc[frame.row_type == 'edge', ['source_id', 'target_id']].to_numpy(np.int64)
        validity = validate(nodes, edges, sample['image_shape'])
        csv_equal = graph_hash(nodes, edges) == graph_hash(prediction['nodes'], prediction['edges'])
        assert selected_equal and csv_equal, 'Copied package prediction/CSV differs from selected graph'
        record.update(inference_receipt_sha256=sha(inference_path), worker_receipt_sha256=sha(worker_path),
            prediction_graph_sha256=graph_hash(prediction['nodes'], prediction['edges']),
            csv_sha256=sha(csv_path), csv_roundtrip_valid=True, csv_validation=validity,
            selected_graph_equal=selected_equal, annotations_unavailable_from_start=True,
            cached_graph_reads_for_prediction=0, source_modules_within_copied_package=True,
            neural_worker_peak_rss_kib=worker['peak_rss_kib'],
            neural_worker_cuda_peak_bytes=worker['cuda_peak_bytes'])
        return record
    from concurrent.futures import ThreadPoolExecutor
    start = time.perf_counter()
    with ThreadPoolExecutor(max_workers=2) as pool:
        records = list(pool.map(one, pilots))
    wall_seconds = time.perf_counter() - start
    if any(record['returncode'] for record in records):
        write_json(ctx.out / 'package_smoke_receipt.json', dict(passed=False, variant=variant,
            actual_copied_package_execution=True, package_manifest_sha256=manifest_hash, pilots=records))
        raise RuntimeError('Copied package inference failed; see per-pilot logs in package_smoke_receipt.json')
    assert all(sha(copied / relative) == expected for relative, expected in manifest['package_files'].items())
    result = dict(passed=True, variant=variant, pilot_names=sorted(r['dataset'] for r in records),
        actual_copied_package_execution=True, copied_package_directory=str(copied),
        attempt_directory=str(attempt_root),
        concurrent_pilot_processes=2, wall_seconds=wall_seconds,
        summed_neural_worker_peak_rss_kib=sum(r['neural_worker_peak_rss_kib'] for r in records),
        summed_neural_worker_cuda_peak_bytes=sum(r['neural_worker_cuda_peak_bytes'] for r in records),
        annotations_unavailable_from_start=True, cached_graph_reads_for_prediction=0,
        selected_graph_parity=sum(r['selected_graph_equal'] for r in records), csv_validation_passed=True,
        source_modules_within_copied_package=True, package_manifest_sha256=manifest_hash,
        policy_sha256=sha(package / 'policy.json'), code_sha256=manifest['code'],
        dependency_sha256={key:manifest[key] for key in ['primary_weights_sha256', 'secondary_weights_sha256',
            'deepcenter_weights_sha256', 'legacy_teacher_model_hashes']}, pilots=records)
    write_json(ctx.out / 'package_smoke_receipt.json', result)
    return result


def export_selected(ctx, variant, *, configuration=None):
    """Exact scored-graph export; fresh-image capability is reported separately."""
    import shutil
    from importlib.metadata import PackageNotFoundError, version
    if configuration is None:
        from .replay import VARIANTS
        if variant in VARIANTS:
            configuration = dict(policy={'repair_settings': VARIANTS[variant]})
        elif variant.startswith('A_'):
            from .association import VARIANTS as association_variants
            if variant in association_variants:
                configuration = dict(policy={'association': association_variants[variant]})
    from .common import (graph_hash, load_graph, now, read_json, sha,
                         validate, write_json)
    policy = (configuration or {}).get('policy', configuration or {})
    if variant not in {'incumbent', 'bypass_motion_bounds'} and not policy:
        raise ValueError('A selected V3 variant requires its concrete measured inference policy')
    counters = deny_annotations(allowed_geff_root=ctx.out / 'fresh')
    attestation_path = ctx.out / 'export_scoring_manifest.json'
    attestation = read_json(attestation_path)
    assert attestation['variant'] == variant and attestation['metric_revision'] == ctx.metric_revision
    expected = attestation['graph_file_sha256']
    assert set(expected) == {row['dataset'] for row in ctx.samples()}
    source_paths = {row['dataset']:(ctx.incumbent(row['dataset']) if variant in {'incumbent', 'bypass_motion_bounds'}
        else ctx.out / 'candidate_graphs' / variant / f"{row['dataset']}.npz") for row in ctx.samples()}
    assert all(sha(path) == expected[name] for name, path in source_paths.items()), 'Scored export source changed'
    destination = ctx.out / 'selected_predictions'
    destination.mkdir(parents=True, exist_ok=True)
    hashes, rows = {}, []
    for row in ctx.samples():
        name = row['dataset']
        source = source_paths[name]
        graph = load_graph(source)
        validation = validate(graph['nodes'], graph['edges'], row['image_shape'])
        target = destination / source.name
        if target.exists():
            assert sha(target) == sha(source), 'Existing selected export differs; explicit new selection required'
        else:
            shutil.copyfile(source, target)
        assert sha(target) == expected[name], 'Export differs from the official scored graph file'
        hashes[name] = sha(target)
        rows.append(dict(dataset=name, graph_hash=graph_hash(graph['nodes'], graph['edges']), **validation))
    receipt = dict(created=now(), variant=variant, hashes=hashes, graphs=rows,
                   annotation_reads=0, attempted_annotation_reads=counters['blocked_reads'],
                   byte_identical_to_scored_graphs=True, samples=len(rows),
                   full_sample_set=len(rows) == 199,
                   official_score_rows_sha256=attestation['official_score_rows_sha256'],
                   scored_graph_attestation_sha256=sha(attestation_path),
                   notebook_sha256=sha(ctx.full / 'harmonic_isolated.py'),
                   selection_configuration=configuration or {})
    write_json(ctx.out / 'selected_prediction_lock.json', receipt)
    write_json(ctx.out / 'winning_config.json', {k: v for k, v in receipt.items() if k not in {'hashes', 'graphs'}})
    package = ctx.out / 'inference_package'
    package.mkdir(parents=True, exist_ok=True)
    for name in ['inference.py', 'fresh.py', 'replay.py', 'context.py', 'common.py', '__init__.py',
                 'features.py', 'disagreements.py', 'association.py', 'association_fresh.py',
                 'event_proposals.py', 'event_model.py', 'decode.py']:
        path = ctx.repo / 'tools' / 'strong_tracker_v3' / name
        if path.exists():
            target = package / 'tools' / 'strong_tracker_v3' / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
    for relative in ['annotation_selection/__init__.py', 'annotation_selection/features.py',
                     'annotation_selection/filter_graph.py', 'strong_tracker_v2/decode.py']:
        target = package / 'tools' / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ctx.repo / 'tools' / relative, target)
    write_json(package / 'policy.json', policy)
    for folder in ['association_models', 'event_models']:
        source = ctx.out / folder
        needed = policy.get('association') if folder == 'association_models' else policy.get('division')
        if needed and source.exists():
            shutil.copytree(source, package / folder, dirs_exist_ok=True)
    for name in ['association_model_lock.json', 'association_config.json', 'event_inference_config.json']:
        source = ctx.out / name
        if source.exists():
            shutil.copyfile(source, package / name)
    (package / 'predict.py').write_text(
        '#!/usr/bin/env python\nimport runpy, sys\nfrom pathlib import Path\n'
        'root = Path(__file__).resolve().parent\nsys.path.insert(0, str(root / "tools"))\n'
        'sys.argv.extend(["--package", str(root)])\n'
        'runpy.run_module("strong_tracker_v3.inference", run_name="__main__")\n')
    (package / 'run.sh').write_text(
        '#!/usr/bin/env bash\nset -euo pipefail\n'
        'v3_package=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)\n'
        'v3_python=${STRONG_TRACKER_PYTHON:-/kaggle/envs/cell-tracking-annotation-selection-v1/bin/python}\n'
        'if [[ ${1:-} == --python ]]; then v3_python=$2; shift 2; fi\n'
        '[[ -x "$v3_python" ]] || { echo "CUDA interpreter unavailable: $v3_python" >&2; exit 2; }\n'
        'export PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 CUDA_VISIBLE_DEVICES=0\n'
        'export OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 MKL_NUM_THREADS=2 POLARS_MAX_THREADS=2\n'
        'export CUBLAS_WORKSPACE_CONFIG=:4096:8\n'
        'export PYTHONPATH="$v3_package/tools"\n'
        'if [[ -n ${LD_LIBRARY_PATH:-} ]]; then\n'
        '  v3_lib=":$LD_LIBRARY_PATH:"\n'
        '  v3_lib=${v3_lib//:\\/usr\\/local\\/cuda\\/lib64:/:}\n'
        '  v3_lib=${v3_lib#:}; v3_lib=${v3_lib%:}\n'
        '  if [[ -n "$v3_lib" ]]; then export LD_LIBRARY_PATH="$v3_lib"; else unset LD_LIBRARY_PATH; fi\n'
        'fi\n'
        'if command -v taskset >/dev/null 2>&1; then\n'
        '  v3_cpus=$("$v3_python" -c \'import os; print(",".join(map(str, sorted(os.sched_getaffinity(0))[:32])))\')\n'
        '  exec taskset -c "$v3_cpus" "$v3_python" "$v3_package/predict.py" "$@"\n'
        'fi\nexec "$v3_python" "$v3_package/predict.py" "$@"\n')
    (package / 'run.sh').chmod(0o755)
    versions = {}
    for dependency in ['numpy', 'scipy', 'torch', 'zarr', 'scikit-learn', 'joblib',
                       'pandas', 'polars', 'tracksdata', 'ilpy', 'geff', 'tqdm']:
        try:
            versions[dependency] = version(dependency)
        except PackageNotFoundError:
            versions[dependency] = 'distribution metadata unavailable'
    write_json(package / 'runtime.json', dict(python=sys.version, interpreter=sys.executable,
        packages=versions, tested_gpu='NVIDIA GeForce RTX 4090', cuda_device=0,
        threads_per_worker=2, annotation_denied_before_dependency_imports=True))
    shutil.copyfile(ctx.out / 'winning_config.json', package / 'winning_config.json')
    write_json(package / 'manifest.json', dict(
        variant=variant, package_kind='portable code with local-weight dependency manifest',
        provenance='Public upstream checkpoints reused supplied embryos; opposite-embryo repair fits remain operational exploratory',
        repair_models_bundled=bool(policy.get('association') or policy.get('division')),
        upstream_models_bundled=False, annotations_bundled=False, cached_predictions_bundled=False,
        notebook_sha256=sha(ctx.full / 'harmonic_isolated.py'),
        notebook_source_path=str(ctx.full / 'harmonic_isolated.py'),
        upstream_tracking_source_root=str(ctx.full / 'tracking_repo'),
        external_checkpoint_paths=dict(
            primary=str(ctx.full / 'tracking_repo/weights/unet_transformer/split_0/edge_predictor_best.pth'),
            secondary=str(ctx.full / 'secondary_seed_weights/unet_transformer/split_0/edge_predictor_best.pth'),
            deepcenter='/kaggle/input/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt'),
        external_teacher_paths={source:str(ctx.v2 / 'models' / source / 'E_hgb.joblib') for source in ['44b6', '6bba']},
        tracking_source_files={str(p.relative_to(ctx.full / 'tracking_repo')): sha(p)
            for folder in ['src', 'scripts'] for p in sorted((ctx.full / 'tracking_repo' / folder).rglob('*.py'))},
        checkpoint_roots=[str(ctx.full / 'tracking_repo/weights'), str(ctx.full / 'secondary_seed_weights')],
        primary_weights_sha256=sha(ctx.full / 'tracking_repo/weights/unet_transformer/split_0/edge_predictor_best.pth'),
        secondary_weights_sha256=sha(ctx.full / 'secondary_seed_weights/unet_transformer/split_0/edge_predictor_best.pth'),
        deepcenter_weights_sha256=sha(Path('/kaggle/input/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt')),
        legacy_teacher_model_hashes={source: sha(ctx.v2 / 'models' / source / 'E_hgb.joblib')
                                     for source in ['44b6', '6bba']},
        code={str(p.relative_to(package)): sha(p) for p in sorted(package.rglob('*.py'))},
        package_files={str(p.relative_to(package)): sha(p) for p in sorted(package.rglob('*'))
                       if p.is_file() and p.name not in {'manifest.json', 'README.md'}}))
    (package / 'README.md').write_text(
        '# Selected inference\n\nSelected variant: `' + variant + '`.\n\n'
        'The exact full-set scored graphs are in the sibling selected_predictions directory. '
        'Fresh execution evidence is recorded separately in sibling fresh_receipt.json '
        '(two neural pilots), fresh_delivery_receipt.json (the full run when complete), '
        'and package_smoke_receipt.json (copied-package image inference). '
        'Read those measured completion receipts before claiming full fresh readiness. '
        'Local CUDA validation does not prove Kaggle runtime compatibility.\n\n'
        'Run `./run.sh --python /path/to/CUDA/python --images IMAGE_DIRECTORY '
        '--output NEW_OUTPUT_DIRECTORY --v1 V1_ARTIFACT_ROOT --v2 V2_ARTIFACT_ROOT '
        '--source-model 44b6` (or the other frozen source model `6bba`). '
        'The source model is explicit; the package never infers an unknown embryo from a filename. '
        'Keep the competition images, original pinned tracking source, primary/secondary '
        'checkpoints and DeepCenter checkpoint available at the explicit RunContext paths. '
        'No labels, evaluator outputs or count estimates are inputs to prediction.\n')
    return receipt


def run(ctx, args):
    from .common import read_json
    config = getattr(args, 'configuration', None)
    return export_selected(ctx, getattr(args, 'variant', None) or 'incumbent',
                           configuration=read_json(Path(config)) if config else None)


if __name__ == '__main__':
    # python -m loads this stdlib-only module, then blocks annotations before
    # RunContext, NumPy, model code, image readers or graph files are imported.
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--variant', default='incumbent')
    parser.add_argument('--images')
    parser.add_argument('--output')
    parser.add_argument('--v1')
    parser.add_argument('--v2')
    parser.add_argument('--source-model', choices=['44b6', '6bba'])
    parser.add_argument('--package')
    parser.add_argument('--configuration')
    parser.add_argument('--stream-repairs', action='store_true')
    parser.add_argument('--benchmark-startup', action='store_true')
    parser.add_argument('--validate-fresh-inputs', action='store_true')
    parser.add_argument('--stream-evidence', action='store_true')
    parser.add_argument('--apply-fresh-selected', action='store_true')
    parser.add_argument('--package-smoke', action='store_true')
    parser.add_argument('--workers', type=int, default=2)
    args = parser.parse_args()
    deny_annotations(allowed_geff_root=Path(args.output) / 'fresh' if args.output else None)
    if args.images:
        if not all([args.output, args.v1, args.v2, args.source_model, args.package]):
            parser.error('Image inference requires --output, --v1, --v2, --source-model and --package')
        predict_directory(args)
        sys.exit(0)
    from .context import RunContext
    if args.package_smoke:
        package_smoke(RunContext.default(), args.variant)
        sys.exit(0)
    if args.apply_fresh_selected:
        from .common import read_json
        if not args.configuration:
            parser.error('--apply-fresh-selected requires a frozen --configuration')
        configuration = read_json(Path(args.configuration))
        apply_fresh_selected(RunContext.default(), args.variant,
                             configuration.get('policy', configuration), args.workers)
        sys.exit(0)
    if args.stream_evidence:
        stream_fresh_evidence(RunContext.default(), args.workers)
        sys.exit(0)
    if args.validate_fresh_inputs:
        validate_fresh_inputs(RunContext.default())
        sys.exit(0)
    if args.benchmark_startup:
        benchmark_startup(RunContext.default())
        sys.exit(0)
    if args.stream_repairs:
        stream_fresh_repairs(RunContext.default())
        sys.exit(0)
    run(RunContext.default(), args)
