"""One predeclared identity/observation-then-event composition, without labels."""
import atexit
import json
from pathlib import Path
import sys


def main():
    job = json.loads(Path(sys.argv[1]).read_text())
    root = Path(job['root'])
    from .guard import install
    guard = install(fresh_root=root, allowed_models=[job['package'], *[d['path'] for d in job['dependencies']]],
                    images=[job['row']['image_path']])
    def audit():
        root.mkdir(parents=True, exist_ok=True)
        (root/'guard.json').write_text(json.dumps(guard)+'\n')
    atexit.register(audit)
    if not guard['installed_before_numerical']:
        raise RuntimeError('Composition startup guard is too late')
    from .resources import Monitor, Lease, cpu_budget
    cpu_budget(4)
    import numpy as np
    import shutil
    import torch
    torch.set_num_threads(2)
    from .common import REPO, digest, graph_hash, load_graph, read_json, save_arrays, save_graph, sha, write_json
    from .serialization import export_csv
    for dep in job['dependencies']:
        if sha(dep['path']) != dep['sha256']:
            raise ValueError('Frozen composition input changed')
    spec = read_json(Path(job['package'])/'frozen_package.json')
    if spec['recipe']['source'] != job['source'] or sha(Path(job['package'])/'frozen_package.json') != job['package_sha256']:
        raise PermissionError('Explicit composition source model mismatch')
    base, graph, native = load_graph(job['P0']), load_graph(job['identity_graph']), load_graph(job['evidence'])
    destination = root/f'{job["row"]["dataset"]}.npz'
    with Monitor(root/'resources.json') as monitor:
        unchanged = all(np.array_equal(graph[k],base[k]) for k in ['nodes','edges'])
        if unchanged:
            division = load_graph(job['division_graph'])
            save_graph(destination, division['nodes'], division['edges'])
            receipt = dict(status='measured', identity_component_exact_P0=True, division_component_reused_after_identity_proof=True,
                graph_hash=graph_hash(division['nodes'],division['edges']), prediction_sha256=sha(destination),
                source=job['source'], model_sha256=spec['weights_sha256'])
        else:
            if np.array_equal(graph['nodes'],base['nodes']):
                from strong_tracker_v3.association_fresh import build_from_inputs
                from strong_tracker_v3.context import RunContext
                ctx = RunContext.default(repo=REPO,out=root,work=root/'structure')
                current, _ = build_from_inputs(ctx,job['row'],graph['nodes'],graph['edges'],load_graph(job['original_raw']),
                    load_graph(job['raw_pre']),dict(nodes=native['old_nodes'],edges=native['old_edges']),native['e_native'],native['e_hgb'],
                    node_features=native['node_features'])
                refresh_kind = 'Same points: exact v3 structure/teacher feature rebuild, verified image values retained'
            else:
                from .native_refresh import refresh
                query_root = root/'fresh_native'; query_root.mkdir(parents=True,exist_ok=True)
                for source in job['fresh_query']:
                    shutil.copyfile(source,query_root/Path(source).name)
                # The neural query was generated by the observation component at
                # these exact current points. Rebuild graph context after its
                # final association step in a new private output directory.
                with Lease(required_gib=8.,wait=True):
                    current = refresh(job['row'],graph,base,native,query_root)
                refresh_kind = 'Changed points: exact observation-component neural query plus fresh current graph/image features'
            save_arrays(root/'current_evidence.npz',**current)
            from .staged_infer import predict_many
            receipt = predict_many(job['row'],graph,current,{'model':Path(job['package'])},{'model':destination},
                                   root/'event',monitor=monitor,wait=True)['model']
            receipt.update(identity_component_exact_P0=False,current_native_features=refresh_kind)
        result = load_graph(destination)
        export_csv(destination.with_suffix('.csv'),job['row']['dataset'],result['nodes'],result['edges'])
        receipt.update(arm=job['experiment'],composition_order=['identity_or_observation','event'],
            identity_model_sha256=job['identity_model_sha256'],event_model_sha256=spec['weights_sha256'],
            no_new_fitted_blend=True,annotation_reads=0)
        write_json(destination.with_suffix('.json'),receipt)


if __name__ == '__main__':
    main()
